### PR TITLE
First try to fix #2

### LINKED ISSUE #2: Displaying of issues in currency list mode is broken
If the user is disconnected and trying to edit the selected currency or select another one as a target, then the issue will be hidden and shown on each state change.

### PR DESCRIPTION
**Pull request by dniHze**
Add last error state to manage error display state. Probably
it should be refactored right into display state as a flag
so activity know nothing about last error state

### CODE REVIEW

File: app/src/main/java/dev/dnihze/revorate/ui/main/MainActivity.kt [hunk 1]
```diff
@@ -43,6 +43,9 @@ class MainActivity : AppCompatActivity() {
 
     private val navigator by lazy(LazyThreadSafetyMode.NONE) { ActivityNavigator(this) }
 
+    // State management helpers
+    private var lastKnownDisplayStateError: MainScreenError? = null
```
Comment (dniHze) [inline app/src/main/java/dev/dnihze/revorate/ui/main/MainActivity.kt]: This is sharing state to view, not OK

Comment (dniHze) [reply app/src/main/java/dev/dnihze/revorate/ui/main/MainActivity.kt]: Refactored and deleted
